- name: Set Yaml
  uses: microsoft/variable-substitution@v1
  with:
    files: ./src/main/resources/application.yml
  env:
    gemini.api.url: ${{secrets.GEMINI_URL}}
    gemini.api.key: ${{secrets.GEMINI_KEY}}